import { ResolvedLocation } from "@/types";

export const INDIAN_TRANSIT_DATABASE: ResolvedLocation[] = [
  // MUMBAI & MAHARASHTRA
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-bom-dadar-rail",
    displayName: "Dadar Railway Station",
    formattedAddress: "Dadar East, Mumbai, Maharashtra 400014",
    locality: "Dadar",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 19.0178,
    longitude: 72.8478,
    placeTypes: ["railway_station"],
    dataSource: "Indian Railways / Mumbai Suburban",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Dadar East · Mumbai Suburban Railway Central & Western Line"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-bom-csmt",
    displayName: "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    formattedAddress: "Fort, Mumbai, Maharashtra 400001",
    locality: "Fort",
    city: "Mumbai",
    district: "Mumbai City",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 18.9400,
    longitude: 72.8353,
    placeTypes: ["railway_station", "landmark"],
    dataSource: "Central Railway Headquarters",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Fort · UNESCO World Heritage Central Railway Terminal"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-bom-bkc",
    displayName: "Bandra Kurla Complex (BKC)",
    formattedAddress: "Bandra East, Mumbai, Maharashtra 400051",
    locality: "Bandra East",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 19.0657,
    longitude: 72.8687,
    placeTypes: ["locality", "landmark"],
    dataSource: "MMRDA Financial Hub",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Bandra East · Commercial Business District"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-bom-andheri-west",
    displayName: "Andheri West Metro & Station",
    formattedAddress: "Andheri West, Mumbai, Maharashtra 400058",
    locality: "Andheri West",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 19.1197,
    longitude: 72.8464,
    placeTypes: ["metro_station", "railway_station"],
    dataSource: "Mumbai Metro Line 1 & Western Railway",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "SV Road · Western Suburban Interchange"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-bom-airport",
    displayName: "Chhatrapati Shivaji Maharaj Int'l Airport (BOM)",
    formattedAddress: "Vile Parle East, Mumbai, Maharashtra 400099",
    locality: "Vile Parle",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 19.0896,
    longitude: 72.8656,
    placeTypes: ["airport"],
    dataSource: "Adani Airports / BOM International",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Terminal 2 · Sahar Airport Road"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-pne-station",
    displayName: "Pune Railway Station",
    formattedAddress: "Agarkar Nagar, Pune, Maharashtra 411001",
    locality: "Agarkar Nagar",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    countryCode: "IN",
    latitude: 18.5289,
    longitude: 73.8744,
    placeTypes: ["railway_station"],
    dataSource: "Central Railway Pune Division",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Pune Junction · Central Railway Interchange"
  },

  // DELHI NCR & NORTH INDIA
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-del-ndls",
    displayName: "New Delhi Railway Station (NDLS)",
    formattedAddress: "Paharganj, New Delhi, Delhi 110055",
    locality: "Paharganj",
    city: "New Delhi",
    district: "Central Delhi",
    state: "Delhi",
    countryCode: "IN",
    latitude: 28.6430,
    longitude: 77.2194,
    placeTypes: ["railway_station", "metro_station"],
    dataSource: "Northern Railway / Delhi Metro Yellow Line",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Ajmeri Gate / Paharganj Entrance · Central Railway Terminal"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-del-rajiv-chowk",
    displayName: "Rajiv Chowk Metro Station (Connaught Place)",
    formattedAddress: "Connaught Place, New Delhi, Delhi 110001",
    locality: "Connaught Place",
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    countryCode: "IN",
    latitude: 28.6328,
    longitude: 77.2197,
    placeTypes: ["metro_station", "landmark"],
    dataSource: "DMRC Yellow & Blue Line Interchange",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Inner Circle · Central DMRC Metro Hub"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-del-kashmere-gate",
    displayName: "Kashmere Gate ISBT & Metro Terminal",
    formattedAddress: "Kashmere Gate, Delhi 110006",
    locality: "Kashmere Gate",
    city: "Delhi",
    district: "North Delhi",
    state: "Delhi",
    countryCode: "IN",
    latitude: 28.6675,
    longitude: 77.2285,
    placeTypes: ["bus_terminal", "metro_station"],
    dataSource: "DTC ISBT & DMRC Triple Line Hub",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Maharana Pratap ISBT · Red, Yellow, Violet Line Hub"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-del-igi-airport",
    displayName: "Indira Gandhi International Airport (DEL)",
    formattedAddress: "Palam, New Delhi, Delhi 110037",
    locality: "Palam",
    city: "New Delhi",
    district: "South West Delhi",
    state: "Delhi",
    countryCode: "IN",
    latitude: 28.5562,
    longitude: 77.1000,
    placeTypes: ["airport", "metro_station"],
    dataSource: "DIAL / Airport Express Metro Line",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Terminal 3 & 1 · Airport Express Corridor"
  },

  // BENGALURU & KARNATAKA
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-blr-silk-board",
    displayName: "Central Silk Board TTMC & Metro",
    formattedAddress: "Silk Board Junction, Hosur Road, Bengaluru, Karnataka 560068",
    locality: "BTM Layout / HSR",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    countryCode: "IN",
    latitude: 12.9172,
    longitude: 77.6228,
    placeTypes: ["bus_terminal", "metro_station"],
    dataSource: "BMTC TTMC & Namma Metro Yellow Line",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Outer Ring Road & Hosur Road Junction"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-blr-hebbal",
    displayName: "Hebbal Bus Station & Flyover",
    formattedAddress: "Hebbal, Bengaluru, Karnataka 560024",
    locality: "Hebbal",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    countryCode: "IN",
    latitude: 13.0359,
    longitude: 77.5970,
    placeTypes: ["bus_terminal", "railway_station"],
    dataSource: "BMTC North Transport Terminal",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Bellary Road Airport Highway Corridor"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-blr-majestic",
    displayName: "KSR Bengaluru City Railway Station & Majestic Bus Stand",
    formattedAddress: "Kempegowda, Sevashrama, Bengaluru, Karnataka 560023",
    locality: "Majestic",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    countryCode: "IN",
    latitude: 12.9781,
    longitude: 77.5697,
    placeTypes: ["railway_station", "bus_terminal", "metro_station"],
    dataSource: "SWR / BMTC / KSRTC / Namma Metro Hub",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Kempegowda Bus Station · Green & Purple Line Metro"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-blr-itpl",
    displayName: "ITPL Whitefield Tech Park",
    formattedAddress: "Whitefield Main Road, Bengaluru, Karnataka 560066",
    locality: "Whitefield",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    countryCode: "IN",
    latitude: 12.9866,
    longitude: 77.7381,
    placeTypes: ["landmark", "metro_station"],
    dataSource: "Pattandur Agrahara Metro Station",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "ITPL Main Entrance · Namma Metro Purple Line"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-blr-airport",
    displayName: "Kempegowda International Airport (BLR)",
    formattedAddress: "Devanahalli, Bengaluru, Karnataka 560300",
    locality: "Devanahalli",
    city: "Bengaluru",
    district: "Bengaluru Rural",
    state: "Karnataka",
    countryCode: "IN",
    latitude: 13.1986,
    longitude: 77.7066,
    placeTypes: ["airport"],
    dataSource: "BIAL International Airport",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Terminal 1 & 2 · KIAS Vayu Vajra Express"
  },

  // KOLKATA & EAST INDIA
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-ccu-howrah",
    displayName: "Howrah Junction Railway Station",
    formattedAddress: "Howrah, West Bengal 711101",
    locality: "Howrah",
    city: "Kolkata",
    district: "Howrah",
    state: "West Bengal",
    countryCode: "IN",
    latitude: 22.5839,
    longitude: 88.3426,
    placeTypes: ["railway_station", "metro_station"],
    dataSource: "Eastern Railway & Green Line Underwater Metro",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Howrah Bridge · Eastern & South Eastern Railway Hub"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-ccu-park-street",
    displayName: "Park Street Metro Station",
    formattedAddress: "Park Street, Kolkata, West Bengal 700016",
    locality: "Park Street",
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    countryCode: "IN",
    latitude: 22.5551,
    longitude: 88.3516,
    placeTypes: ["metro_station", "landmark"],
    dataSource: "Kolkata Metro Blue Line Line 1",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Mother Teresa Sarani · Central Heritage Corridor"
  },

  // CHENNAI & TAMIL NADU
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-maa-central",
    displayName: "Chennai Central Railway Station (MAS)",
    formattedAddress: "Kannappar Thidai, Periyamet, Chennai, Tamil Nadu 600003",
    locality: "Periyamet",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    countryCode: "IN",
    latitude: 13.0827,
    longitude: 80.2707,
    placeTypes: ["railway_station", "metro_station"],
    dataSource: "Southern Railway & CMRL Metro Central",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Puratchi Thalaivar Dr. M.G.R. Central"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-maa-cmbt",
    displayName: "CMBT Koyambedu Bus Terminal & Metro",
    formattedAddress: "Koyambedu, Chennai, Tamil Nadu 600107",
    locality: "Koyambedu",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    countryCode: "IN",
    latitude: 13.0694,
    longitude: 80.1948,
    placeTypes: ["bus_terminal", "metro_station"],
    dataSource: "MTC & SETC Intercity Terminal",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Chennai Mofussil Bus Terminus"
  },

  // HYDERABAD & TELANGANA
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-hyd-secunderabad",
    displayName: "Secunderabad Junction Railway Station",
    formattedAddress: "Secunderabad, Telangana 500003",
    locality: "Secunderabad",
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    countryCode: "IN",
    latitude: 17.4339,
    longitude: 78.5016,
    placeTypes: ["railway_station", "metro_station"],
    dataSource: "South Central Railway & Hyderabad Metro Blue Line",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Station Road · South Central Railway HQ"
  },
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-hyd-hitech-city",
    displayName: "HITECH City Metro Station & Cyberabad",
    formattedAddress: "HITECH City, Madhapur, Hyderabad, Telangana 500081",
    locality: "Madhapur",
    city: "Hyderabad",
    district: "Koti",
    state: "Telangana",
    countryCode: "IN",
    latitude: 17.4474,
    longitude: 78.3762,
    placeTypes: ["metro_station", "landmark"],
    dataSource: "Hyderabad Metro Rail Blue Line",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Cyber Towers · IT Corridor Hub"
  },

  // AHMEDABAD & GUJARAT
  {
    provider: "indian_transit_db",
    providerPlaceId: "in-amd-kalupur",
    displayName: "Ahmedabad Junction (Kalupur Station)",
    formattedAddress: "Kalupur, Ahmedabad, Gujarat 380002",
    locality: "Kalupur",
    city: "Ahmedabad",
    district: "Ahmedabad",
    state: "Gujarat",
    countryCode: "IN",
    latitude: 23.0274,
    longitude: 72.6012,
    placeTypes: ["railway_station", "metro_station"],
    dataSource: "Western Railway & GMRC Metro Rail",
    retrievedAt: new Date().toISOString(),
    secondaryAddress: "Kalupur Railway Terminal · East-West Metro Line"
  }
];
